#' Match Species Records Inside Problem Intervals
#'
#' @description
#' Matches `Species_records_camera` rows against camera-problem intervals
#' generated by [check_problem_intervals()].
#'
#' For each dataset, it reshapes `ProblemX_interval` columns to long format,
#' joins by `Structure_id` and `Camera_id`, and keeps records whose
#' `Record_date` is within at least one problem interval.
#'
#' Returned rows include a `problem_match` label (one or more `ProblemX`
#' values) and preserve interval audit context from the camera-trap table.
#'
#' @param sps_list Named list of data frames from `Species_records_camera`.
#' @param ct_problem_list Named list returned by [check_problem_intervals()].
#'
#' @return A tibble with all matched records across datasets. Empty datasets
#'   are discarded.
#' @export
check_records_in_problem_intervals <- function(sps_list, ct_problem_list) {
  datasets <- intersect(names(sps_list), names(ct_problem_list))

  datasets |>
    purrr::set_names() |>
    purrr::map(\(dataset) {
      sps_df <- sps_list[[dataset]] |>
        dplyr::mutate(record_row = dplyr::row_number() + 1L, .before = 1)

      ct_df <- ct_problem_list[[dataset]]

      if (is.null(ct_df) || nrow(ct_df) == 0) {
        return(dplyr::slice_head(sps_df, n = 0))
      }

      interval_cols <- names(ct_df) |>
        stringr::str_subset("^Problem[0-9]+_interval$")

      if (length(interval_cols) == 0) {
        return(dplyr::slice_head(sps_df, n = 0))
      }

      ct_tagged <- ct_df |>
        dplyr::mutate(ct_row_id = dplyr::row_number(), .before = 1)

      intervals_long <- ct_tagged |>
        dplyr::select(
          ct_row_id,
          Structure_id,
          Camera_id,
          install_period,
          dplyr::all_of(interval_cols)
        ) |>
        tidyr::pivot_longer(
          cols = dplyr::all_of(interval_cols),
          names_to = "problem_label",
          values_to = "problem_interval",
          values_drop_na = TRUE
        ) |>
        dplyr::mutate(
          problem_label = stringr::str_remove(problem_label, "_interval")
        )

      if (nrow(intervals_long) == 0) {
        return(dplyr::slice_head(sps_df, n = 0))
      }

      matched_long <- sps_df |>
        dplyr::inner_join(
          intervals_long,
          by = c("Structure_id", "Camera_id"),
          relationship = "many-to-many"
        ) |>
        dplyr::filter(
          !is.na(Record_date),
          lubridate::`%within%`(Record_date, problem_interval)
        )

      if (nrow(matched_long) == 0) {
        return(dplyr::slice_head(sps_df, n = 0))
      }

      problem_by_record <- matched_long |>
        dplyr::group_by(record_row, ct_row_id) |>
        dplyr::summarise(
          problem_match = paste(sort(unique(problem_label)), collapse = ", "),
          .groups = "drop"
        )

      sps_df |>
        dplyr::inner_join(problem_by_record, by = "record_row") |>
        dplyr::left_join(
          ct_tagged |>
            dplyr::select(-Structure_id, -Camera_id),
          by = "ct_row_id",
          relationship = "many-to-one"
        ) |>
        dplyr::relocate(problem_match, .after = install_period) |>
        dplyr::mutate(Record_date = lubridate::as_date(Record_date)) |>
        dplyr::select(
          -dplyr::any_of(c(
            "ct_row_id",
            "Record_time",
            "Record_criteria",
            "Behavior",
            "Start_date",
            "End_date",
            "check_problem"
          )),
          -dplyr::ends_with("_to"),
          -dplyr::ends_with("_from")
        )
    }) |>
    purrr::discard(~ nrow(.x) == 0) |>
    dplyr::bind_rows(.id = "dataset")
}
